djangoproject/djangoproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as authviews
from django.conf import settings
from tureview import views as tuview
from tureview import rest as turest

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^$', tuview.home, name='home'),
    url(r'^search', tuview.search, name='search'),
    url(r'^course/(?P<code>[0-9a-zA-Z]{4,8})/$', tuview.course,
        name='course'),
    url(r'^course/(?P<code>[0-9a-zA-Z]{4,8})/review/$', tuview.review,
        name='review'),
    url(r'^course/(?P<code>[0-9a-zA-Z]{4,8})/thumbs/$', turest.thumbs, name='thumbs'),
    url(r'^accounts/login/$', authviews.login, name='login'),
    url(r'^accounts/logout/$', authviews.logout, {'next_page': '/'},
        name='logout'),
    url(r'^accounts/register$', tuview.register, name='register'),
    url(r'^accounts/profile/$', tuview.profile, name='profile'),
    url(r'^accounts/profile/thumbs/$', turest.thumbsProfile, name='profileThumbs'),
    url(r'^accounts/profile/(?P<username>.+)/thumbs/$', turest.thumbsUserprofile, name='userprofileThumbs'),
    url(r'^accounts/profile/(?P<username>.+)/$', tuview.userprofile, name='userprofile'),
    url(r'^api/search$', turest.search)

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoproject/tureview/models.py
from django.db import models
from django.utils import timezone


# Create your models here.


class Teacher(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Course(models.Model):
    id = models.CharField(max_length=6, primary_key=True)
    name = models.CharField(max_length=199)
    descriptionShort = models.CharField(max_length=200)
    descriptionLong = models.TextField()
    averageRating = models.FloatField(default=0)
    reviewNumber = models.IntegerField(default=0)

    FACULTY_OPTIONS = (
        ('BMT', 'Biomedishe Technologie'),
        ('BK', 'Bouwkunde'),
        ('ESoE', 'Eindhoven School of Education'),
        ('EE', 'Electrical Engineering'),
        ('ID', 'Industrial Design'),
        ('TUE', 'Technische Universiteit Eindhoven'),
        ('IEID', 'Industrial Engineering & Innovation Sciences'),
        ('ST', 'Scheikundige Technologie'),
        ('TN', 'Technishe Natuurkunde'),
        ('wbtk', 'Werktuigboukunde'),
        ('WI', 'Wiskunde & Informatica')
    )
    faculty = models.CharField(choices=FACULTY_OPTIONS, max_length=4, default='BK')

    teachers = models.ManyToManyField(Teacher)

    def __str__(self):
        return self.id + " " + self.name

    def getAverage(self):
        return "{0:.1f}".format(self.averageRating)


class Timeslot(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    letter = models.CharField(max_length=1, choices=((i, i) for i in 'abcdex'))
    quartile = models.CharField(max_length=2,
                                choices=tuple((str(i), str(i))
                                              for i in range(1, 5)))
    year = models.IntegerField()

    def __str__(self):
        return str(self.course) + " in " + str(self.year) + " Q" + str(self.quartile) + " timeslot " + str(
            self.letter).upper()


class Student(models.Model):
    user = models.OneToOneField('auth.User', primary_key=True, on_delete=models.CASCADE)
    startYear = models.IntegerField()
    MAJOR_OPTIONS = (
        ('sfs', 'Software Science'),
        ('ws', 'Web Science'),
        ('id', 'Industrial Design'),
        ('png', 'Psychology & Technology'),
        ('mwt', 'medishe wetenshappen en technologie'),
        ('ie', 'Industrial Engineering'),
        ('si', 'Sustainable Innovation'),
        ('ds', 'Data Science'),
        ('wtbk', 'Werktuigboukunde'),
        ('aubs', 'Bouwkunde'),
        ('au', 'Automotive Technology'),
        ('bmt', 'Biomedishe Technologie'),
        ('cec', 'Chemical Engineering & Chemisty'),
        ('cse', 'Computer Science en Engineering'),
        ('ntk', 'Applied Physics'),
        ('wis', 'Applied Mathematics'),
        ('ee', 'Electrical Engineering')
    )
    major = models.CharField(max_length=16, choices=MAJOR_OPTIONS)

    def __str__(self):
        return self.user.username


class Review(models.Model):
    thumbsUp = models.ManyToManyField(Student, related_name="thumbsUp")
    thumbsDown = models.ManyToManyField(Student, related_name="thumbsDown")
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    reviewShort = models.CharField(max_length=200)
    reviewLong = models.TextField()
    date = models.DateField(default=timezone.now)
    timeslot = models.ForeignKey(Timeslot, on_delete=models.CASCADE)
    ratingOverall = models.IntegerField(default=0)
    ratingInf = models.IntegerField(default=0)
    ratingTime = models.IntegerField(default=0)
    ratingRele = models.IntegerField(default=0)
    ratingDiff = models.IntegerField(default=0)

djangoproject/tureview/forms.py
from django import forms as dforms
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password
from .models import Student, Timeslot
from .widgets import CounterWidget, StarWidget


class RegistrationForm(dforms.Form):
    username = dforms.CharField(label='username')
    password = dforms.CharField(widget=dforms.PasswordInput, label='password')
    password_2 = dforms.CharField(widget=dforms.PasswordInput, label='confirm password')
    major = dforms.ChoiceField(label='major', choices=Student.MAJOR_OPTIONS)
    startyear = dforms.IntegerField(label='start year')

    def clean_password(self):
        password = self.cleaned_data['password']
        validate_password(password)
        return password

# uses widget starWidget.html (this can be used to prettify the for now 0's to make them stars)
class ReviewForm(dforms.Form):
    def __init__(self, timeSlotOptions, *args, **kwargs):
        dforms.Form.__init__(self, *args, **kwargs)
        self.fields["timeslot"].choices = timeSlotOptions
    summary = dforms.CharField(widget=dforms.TextInput(
        attrs={'placeholder': 'A once-sentence summary of your review'}))
    rating = dforms.IntegerField(label="overall rating", widget=CounterWidget())
    infrating = dforms.IntegerField(label="informative", widget=StarWidget())
    timerating = dforms.IntegerField(label="time consuming", widget=StarWidget())
    relerating = dforms.IntegerField(label="relevant to study", widget=StarWidget())
    diffrating = dforms.IntegerField(label="difficulty", widget=StarWidget())
    content = dforms.CharField(widget=dforms.Textarea())
    year = dforms.IntegerField(label='year course taken', initial=2018, widget=dforms.NumberInput(
        attrs={'min': '1900', 'max': '2500'}
    ))
    timeslot = dforms.ChoiceField(label='quartile taken', choices=())
    def clean_timeslot(self):
        slot = self.cleaned_data['timeslot'].split(',')
        return slot

djangoproject/tureview/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.db.models import Avg, Count
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.utils import timezone
from .models import Review, Course, Student, Timeslot
from .forms import RegistrationForm, ReviewForm


def home(request):
    topcourses = Course.objects.all().order_by('-averageRating')[:3]
    return render(request, "tureview/home.html", {'topcourses': topcourses})


def search(request):
    faculties = Course.FACULTY_OPTIONS
    return render(request, "tureview/search.html", {"faculties": faculties,
                                                    "letters": [(i, i.upper()) for i in 'abcdex'],
                                                    "quartiles": [(i, "Q" + str(i)) for i in range(1, 5)]})


def course(request, code):
    if request.user.is_authenticated:
        student = Student.objects.get(user=request.user)
    code = code.upper()
    try:
        course = Course.objects.get(id__iexact=code)
    except Course.DoesNotExist:
        return HttpResponse("course \"" + str(code) + "\" does not exist")
    #reviews = Review.objects.filter(timeslot__course=course).order_by('date')
    reviews = Review.objects.filter(timeslot__course=course).order_by('date').annotate(upvotes=Count('thumbsUp')-Count('thumbsDown')).order_by('-upvotes')
    if request.user.is_authenticated:
        for review in reviews:
            if Review.objects.filter(pk=review.pk, thumbsUp__pk=student.pk).exists():
                review.up = True
            else:
                review.up = False
            if Review.objects.filter(pk=review.pk, thumbsDown__pk=student.pk).exists():
                review.down = True
            else:
                review.down = False

    return render(request, "tureview/course.html",
                  {'course': course, 'reviews': reviews})


@login_required
def review(request, code):

    slots = Timeslot.objects.filter(course__id__iexact=code)
    gys = [(i.quartile, i.letter) for i in slots]
    gys = set(gys)
    gys2 = [(str(i[0])+","+str(i[1]), "Q"+str(i[0])+" timeslot "+str(i[1])) for i in gys]

    if request.method == "POST":
        form = ReviewForm(gys2, request.POST)
        if form.is_bound and form.is_valid():
            cleaned = form.cleaned_data
            timeslots = Timeslot.objects.filter(
                course__id__iexact=code).filter(
                year=cleaned["year"]).filter(
                letter=cleaned["timeslot"][1]).filter(
                quartile=cleaned["timeslot"][0])
            try:
                slot0 = timeslots[0]
            except IndexError:
                form.add_error("timeslot", "The course "+str(code)+" was not offered in this year, quartile and timeslot")
                slot0 = None

            if slot0:
                assert slot0, repr(slot0)

                student = Student.objects.get(user=request.user)

                review = Review()
                review.date = timezone.now()
                review.reviewLong = cleaned["content"]
                review.reviewShort = cleaned["summary"]
                review.student = student
                review.timeslot = slot0
                review.ratingOverall = cleaned["rating"]
                review.ratingInf = cleaned["infrating"]
                review.ratingTime = cleaned["timerating"]
                review.ratingRele = cleaned["relerating"]
                review.ratingDiff = cleaned["diffrating"]
                review.save()

                try:
                    course = Course.objects.get(id__iexact=code)
                except Course.DoesNotExist:
                    return HttpResponse("unexpeted database error (course appears to be deleted")

                average = Review.objects.filter(timeslot__course = course).aggregate(
                    Avg('ratingOverall'), Count('ratingOverall'))
                course.averageRating = average["ratingOverall__avg"]
                course.reviewNumber = average["ratingOverall__count"]
                course.save()

                return HttpResponseRedirect("..")

    else:
        form = ReviewForm(gys2)
    course = slots[0].course
    return render(request, "tureview/review.html",
        {"slots": slots, "form": form, "course": course})


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
    else:
        form = RegistrationForm()
    if form.is_bound and form.is_valid():
        cleaned = form.cleaned_data
        if cleaned['password'] == cleaned['password_2']:
            try:
                existingUser = User.objects.get(username=cleaned["username"])

                form.add_error("username", "username allready taken")
            except User.DoesNotExist:

                user = User.objects.create_user(cleaned["username"], "", cleaned["password"])
                user.save()
                student = Student()
                student.user = user
                student.major = cleaned["major"]
                student.startYear = cleaned["startyear"]
                student.save()

                login(request, user)
                return HttpResponseRedirect("/accounts/profile")
        else:
            form.add_error("password_2", "Passwords do not match")
    return render(request, "registration/register.html", {"form": form})

# Please don't remove
@login_required
def profile(request):
    user = request.user
    student = Student.objects.get(user=user)
    reviews = Review.objects.filter(student=request.user.student)
    thumbsUp = 0
    thumbsDown = 0
    for review in reviews:
        thumbsUp += review.thumbsUp.count()
        thumbsDown += review.thumbsDown.count()
        if Review.objects.filter(pk=review.pk, thumbsUp__pk=student.pk).exists():
            #thumbsUp += 1
            review.up = True
        else:
            review.up = False
        if Review.objects.filter(pk=review.pk, thumbsDown__pk=student.pk).exists():
            #thumbsDown += 1
            review.down = True
        else:
            review.down = False
    return render(request, "tureview/profile.html", {'user': user,
        'student': student, 'reviews': reviews, 'upTotal': thumbsUp, 'downTotal': thumbsDown})

def userprofile(request, username):
    current_student_set = False
    if request.user.is_authenticated:
        current_student = Student.objects.get(user=request.user)
        current_student_set = True
    user = User.objects.get(username=username)
    student = Student.objects.get(user=user)
    reviews = Review.objects.filter(student=student)
    thumbsUp = 0
    thumbsDown = 0
    for review in reviews:
        #if Review.objects.filter(pk=review.pk, thumbsUp__pk=student.pk).exists():
            #thumbsUp += 1
        #if Review.objects.filter(pk=review.pk, thumbsDown__pk=student.pk).exists():
            #thumbsDown += 1
        thumbsUp += review.thumbsUp.count()
        thumbsDown += review.thumbsDown.count()
        if current_student_set:
            if Review.objects.filter(pk=review.pk, thumbsUp__pk=current_student.pk).exists():
                review.up = True
            else:
                review.up = False
            if Review.objects.filter(pk=review.pk, thumbsDown__pk=current_student.pk).exists():
                review.down = True
            else:
                review.down = False
    return render(request, "tureview/profile.html", {'user': user,
        'student': student, 'reviews': reviews, 'upTotal': thumbsUp, 'downTotal': thumbsDown})

djangoproject/tureview/templates/tureview/course.html
{% extends 'tureview/base.html' %}
{% load static %}
{% load costum_filters %}
{% block title %} Course {{ course.id }} {% endblock %}
{% csrf_token %}
{% block content %}

<!-- section voor laag 1-->
<section class="page-section background">
  <!-- section voor laag 2-->
    <div class="container.course">
      <div class="row.course">
              <div class="coursedescription">
                <div class="section-heading mb-4">
                    <div>
                      <span class="tbig uppercase coursecode">{{course.id}}</span>
                        <span class="tbig">{{ course.name }}</span>
                      <span class="tbig" style="float: right;"><span class="tsmall">average rating:</span> {{ course.getAverage }} </span>
                    </div>
                    <div>
                      <span class="faculty signika tbig"> {{ course.get_faculty_display }}</span>
                      </div>
                    <div class="signika tsmall margin">
                      {{course.descriptionLong}}
                    </div>
                  </div>
            </div>
            <div class="aligncenter">
              <a class="btn btn-primary btn-xl center" href="review" style=":margin-bottom:0 !important;">Write your own review</a>
          </div>
        </div>
    </div>

    <section style="width:100%; padding:5px;">
      <!-- accordion voor laag 3.1-->
      {% for review in reviews %}
        <div class="whitebox">
          <div class="cta-inner rounded">
            <div class="section-heading mb-4">
              <table style="border-collapse: collapse; width: 100%;">
                <colgroup>
                   <col span="1" style="width: 15%;">
                   <col span="1" style="width: 70%;">
                   <col span="1" style="width: 15%;">
                </colgroup>
                <tr>
                  <th class="tbig" colspan="2">{{ review.reviewShort }}</th>
                  <th class="tbig" style="text-align: right;">{{review.ratingOverall}}</th>
                </tr>
                <tr>
                  <td class="tsmall"><a href="{% url 'userprofile' username=review.student %}">{{ review.student.user.username }}</a> </td>
                  <td class="tsmall" style="text-align: right; overflow: visible;" colspan="2">{{ review.date }}</td>
                </tr>
              </table>
              <div>
                <div class="tsmall" id="panel" style="display:none;">started this course as a {{ review.timeslot.year|yearStudent:review.student.startYear }} year student <br> from: {{ review.student.get_major_display }}</br></br>
                  <p class="italic">{{ review.reviewLong }}</p>
                  <p>
                    <table style="border-collapse: collapse;">
                      <colgroup>
                         <col span="1" style="width: auto;">
                         <col span="1" style="width: 10px;">
                         <col span="1" style="width: auto;">
                      </colgroup>
                      <tr>
                        <td><b>Informative: </b></td>
                        <td></td>
                        <td><span id="ratingInf"><span></td>
                      </tr>
                      <tr>
                        <td><b>Time consuming:</b></td>
                        <td></td>
                        <td><span id="ratingTime"></span></td>
                      </tr>
                      <tr>
                        <td><b>Relevant: </b></td>
                        <td></td>
                        <td><span id="ratingRele"></span></td>
                      </tr>
                      <tr>
                        <td><b>Difficult: </b></td>
                        <td></td>
                        <td><span id="ratingDiff"></span></td>
                      </tr>
                    </table>
                    <input id="ratingInf-value" type="hidden" value="{{ review.ratingInf }}" ></input>
                    <input id="ratingTime-value" type="hidden" value="{{ review.ratingTime }}" ></input>
                    <input id="ratingRele-value" type="hidden" value="{{ review.ratingRele }}" ></input>
                    <input id="ratingDiff-value" type="hidden" value="{{ review.ratingDiff }}" ></input>
                  </p>
                </div>
                <div id="flip">

                  <div class="aligncenter">
                    <button class="btn btn-primary showMore">
                      <i class="fa fa-chevron-down" aria-hidden="true"></i>
                      Show more
                    </button>
                    <button class="btn btn-primary showLess" style="display: none;">
                      <i class="fa fa-chevron-up" aria-hidden="true"></i>
                      Show less
                    </button>
                  </div>
                </div>
              </div>
              <div class="aligncenter">
                <span class="tsmall" id="thumbsUpCount"> {{review.thumbsUp.count}} </span>
                {% if not request.user.is_authenticated %}<a href="{% url 'login' %}">{% endif %}
                <button class="btn btn-primary thumbsUp" id="thumbsUp">
                  {% if review.up == True %}
                  <i class="fa fa-thumbs-up active" style=aria-hidden="true"></i>
                  <i class="fa fa-thumbs-o-up inactive" style="display: none;" style=aria-hidden="true"></i>
                  {% else %}
                  <i class="fa fa-thumbs-up active" style="display: none;" style=aria-hidden="true"></i>
                  <i class="fa fa-thumbs-o-up inactive" style=aria-hidden="true"></i>
                  {% endif %}
                </button>
                {% if not request.user.is_authenticated %}</a>{% endif %}
                <span class="tsmall" id="thumbsDownCount"> {{review.thumbsDown.count}} </span>
                {% if not request.user.is_authenticated %}<a href="{% url 'login' %}">{% endif %}
                <button class="btn btn-primary thumbsDown" id="thumbsDown">
                  {% if review.down == True %}
                  <i class="fa fa-thumbs-down active" style=aria-hidden="true"></i>
                  <i class="fa fa-thumbs-o-down inactive" style="display: none;" style=aria-hidden="true"></i>
                  {% else %}
                  <i class="fa fa-thumbs-down active" style="display: none;" style=aria-hidden="true"></i>
                  <i class="fa fa-thumbs-o-down inactive" style=aria-hidden="true"></i>
                  {% endif %}
                </button>
                {% if not request.user.is_authenticated %}</a>{% endif %}
                <input id="review-pk" type="hidden" value="{{ review.pk }}" ></input>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </section>
</section>
<script src="{% static 'javascript/ajax.js' %}" defer></script>
<script src="{% static 'javascript/course.js' %}" defer></script>
{% endblock %}

djangoproject/tureview/templates/tureview/profile.html
{% extends 'tureview/base.html' %}
{% load static %}
{% load costum_filters %}
{% block title %} Profile {{ user.username }} {% endblock %}
{% csrf_token %}
{% block content %}
<section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-12">

          <h1 class="username" ><i class="user fa fa-user" aria-hidden="true"></i><br><br>  {{ user.username }} </h1>
          <p class="userinfo">
            <b>Bachelor: </b> {{ student.get_major_display }} <br>
            <b>Start year: </b> {{ student.startYear }} <br>
            <b>Received thumbs up: </b> {{ upTotal }} <br> <!-- not working -->
            <b>Received thumbs down: </b> {{ downTotal }} <br> <!-- not working -->
            <b>Total reviews: </b> {{ reviews.count }} <br>
          </p>
        </div>
        <div class="row">
          <div class="col-12">
            <h1 class="userreview">Reviews of {{ user.username }} </h1>
          </div>
          {% for review in reviews %}
          <div class="whitebox">
            <div class="cta-inner rounded">
              <div class="section-heading mb-4">
                <table style="border-collapse: collapse; width: 100%;">
                  <colgroup>
                     <col span="1" style="width: 15%;">
                     <col span="1" style="width: 70%;">
                     <col span="1" style="width: 15%;">
                  </colgroup>
                  <tr>
                    <th colspan="2"><a class="link-course" href="{% url 'course' code=review.timeslot.course.id %}">{{ review.timeslot.course }}</a></th>
                    <th class="tbig" style="text-align: right;">{{review.ratingOverall}}</th>
                  </tr>
                  <tr>
                    <td class="text-small" colspan="2">{{ review.reviewShort }}</td>
                    <td class="tsmall" style="text-align: right; overflow: visible;" colspan="2">{{ review.date }}</td>
                  </tr>
                </table>
                <div>
                  <div class="tsmall" id="panel" style="display:none;">started this course as a {{ review.timeslot.year|yearStudent:review.student.startYear }} year student <br> from: {{ review.student.get_major_display }}</br></br>
                    <p>{{ review.reviewLong }}</p>
                    <p>
                      <table style="border-collapse: collapse;">
                        <colgroup>
                           <col span="1" style="width: auto;">
                           <col span="1" style="width: 10px;">
                           <col span="1" style="width: auto;">
                        </colgroup>
                        <tr>
                          <td><b>Informative: </b></td>
                          <td></td>
                          <td><span id="ratingInf"><span></td>
                        </tr>
                        <tr>
                          <td><b>Time consuming:</b></td>
                          <td></td>
                          <td><span id="ratingTime"></span></td>
                        </tr>
                        <tr>
                          <td><b>Relevant: </b></td>
                          <td></td>
                          <td><span id="ratingRele"></span></td>
                        </tr>
                        <tr>
                          <td><b>Difficult: </b></td>
                          <td></td>
                          <td><span id="ratingDiff"></span></td>
                        </tr>
                      </table>
                      <input id="ratingInf-value" type="hidden" value="{{ review.ratingInf }}" ></input>
                      <input id="ratingTime-value" type="hidden" value="{{ review.ratingTime }}" ></input>
                      <input id="ratingRele-value" type="hidden" value="{{ review.ratingRele }}" ></input>
                      <input id="ratingDiff-value" type="hidden" value="{{ review.ratingDiff }}" ></input>
                    </p>
                  </div>
                  <div id="flip">

                    <div class="aligncenter">
                      <button class="btn btn-primary showMore">
                        <i class="fa fa-chevron-down" aria-hidden="true"></i>
                        Show more
                      </button>
                      <button class="btn btn-primary showLess" style="display: none;">
                        <i class="fa fa-chevron-up" aria-hidden="true"></i>
                        Show less
                      </button>
                    </div>
                  </div>
                </div>
                <div class="aligncenter">
                  <span class="tsmall" id="thumbsUpCount"> {{review.thumbsUp.count}} </span>
                  {% if not request.user.is_authenticated %}<a href="{% url 'login' %}">{% endif %}
                  <button class="btn btn-primary thumbsUp" id="thumbsUp">
                    {% if review.up == True %}
                    <i class="fa fa-thumbs-up active" style=aria-hidden="true"></i>
                    <i class="fa fa-thumbs-o-up inactive" style="display: none;" style=aria-hidden="true"></i>
                    {% else %}
                    <i class="fa fa-thumbs-up active" style="display: none;" style=aria-hidden="true"></i>
                    <i class="fa fa-thumbs-o-up inactive" style=aria-hidden="true"></i>
                    {% endif %}
                  </button>
                  {% if not request.user.is_authenticated %}</a>{% endif %}
                  <span class="tsmall" id="thumbsDownCount"> {{review.thumbsDown.count}} </span>
                  {% if not request.user.is_authenticated %}<a href="{% url 'login' %}">{% endif %}
                  <button class="btn btn-primary thumbsDown" id="thumbsDown">
                    {% if review.down == True %}
                    <i class="fa fa-thumbs-down active" style=aria-hidden="true"></i>
                    <i class="fa fa-thumbs-o-down inactive" style="display: none;" style=aria-hidden="true"></i>
                    {% else %}
                    <i class="fa fa-thumbs-down active" style="display: none;" style=aria-hidden="true"></i>
                    <i class="fa fa-thumbs-o-down inactive" style=aria-hidden="true"></i>
                    {% endif %}
                  </button>
                  {% if not request.user.is_authenticated %}</a>{% endif %}
                  <input id="review-pk" type="hidden" value="{{ review.pk }}" ></input>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
</section>
<script src="{% static 'javascript/ajax.js' %}" defer></script>
<script src="{% static 'javascript/course.js' %}" defer></script>
<script>
  $.ajaxSetup({data: {
    csrfmiddlewaretoken: '{{ csrf_token }}'
  }});
</script>
{% endblock %}

djangoproject/tureview/templates/tureview/review.html
<!-- First base.html will be loaded and the block content will be placed in the base page -->
{% extends 'tureview/base.html' %}
{% load static %}

<!-- Used for creating nice forms -->
{% load widget_tweaks %}

<!-- Used for the title in base.html -->
{% block title %} Review {% endblock %}

{% block content %}
<section class="page-section background">
    <div class="container">
      <h1 class="tbig margin">Writing a review for {{ course.id }} - {{ course.name }}</h1>
      <form method="post" novalidate>
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field }}
        {% endfor %}

        {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}

        {% for field in form.visible_fields %}
          <div class="form-group">
            {{ field.label_tag }}

            {% if form.is_bound %}
              {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                  <div class="invalid-feedback" style="color: blue;">
                    {{ error }}
                  </div>
                {% endfor %}
              {% else %}
                {% render_field field class="form-control is-valid" %}
              {% endif %}
            {% else %}
              {% render_field field class="form-control" %}
            {% endif %}

            {% if field.help_text %}
              <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
          </div>
        {% endfor %}

        <button type="submit" class="margin btn btn-primary">Submit</button>
      </form>

    </div>
</section>
{% endblock %}